language: java
jdk:
- oraclejdk7

deploy:
  provider: heroku
  api_key:
    secure: Nm/evyX4yvjP44THa5whXhcId061oCExrQF/TTRyXWv6ArwjRjEK2vbH+RhhjRzKEfB30alna1dwI1Md1hLP9xMCUrcR7Yg336B2guKxVh6zNv9noNTuVmaABuZBOidor7YSYBWNcrkioV5PHTLwoP31HNIChQNIzd2YkUOJ6A0=
  app: cryptic-depths-9874
  on:
    repo: robparrott/web-hello-world

before_install:
- openssl aes-256-cbc -K $encrypted_6b883e898529_key -iv $encrypted_6b883e898529_iv
  -in .travis/web-helloworld-production-deploy.enc -out .travis/web-helloworld-production-deploy.key -d

after_success:
  - source .travis/ssh-setup.sh
  - git remote add deploy git@github.com:robparrott/web-hello-world-deploy.git
  - git config --global push.default matching
  - git ls-files
  - git branch -av
  - git push deploy master
  - echo "Completed push..."
