language: java
jdk:
- oraclejdk7
deploy:
  provider: heroku
  api_key:
    secure: Nm/evyX4yvjP44THa5whXhcId061oCExrQF/TTRyXWv6ArwjRjEK2vbH+RhhjRzKEfB30alna1dwI1Md1hLP9xMCUrcR7Yg336B2guKxVh6zNv9noNTuVmaABuZBOidor7YSYBWNcrkioV5PHTLwoP31HNIChQNIzd2YkUOJ6A0=
  app: web-hello-world
  on:
    repo: robparrott/web-hello-world
